version: 1
services:
  # Service Frontend (Static Site)
  - type: static
    name: spotbulle-mentor
    env: static
    region: frankfurt
    buildCommand: |
      cd front-end &&
      npm install &&
      npm run build
    publishDir: front-end/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://spotbulle-backend-01ax.onrender.com/api/v1
