version: 1
services:
  # Service Backend (FastAPI)
  - type: web
    name: spotbulle-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildFilter:
      paths:
        - "backend/**"
    buildCommand: |
      pip install --upgrade pip
      python fix_dependencies.py
      pip install -r requirements.txt
      python create_tables.py
      alembic upgrade head 
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --forwarded-allow-ips="*"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: spotbulle-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BUCKET_NAME
        sync: false

  # Service Frontend (StaticSite)
  - type: web
    name: spotbulle-front-end
    env: static
    # Ligne region: frankfurt supprimée ici
    plan: free
    rootDir: front-end
    buildFilter:
      paths:
        - "front-end/**"
    buildCommand: |
      npm install
      npm run build
      echo "Contenu du répertoire dist après build:"
      ls -la ./dist
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.19.1
        
databases:
  - name: spotbulle-db
    region: frankfurt
    plan: free
    databaseName: spotbulle_production
    user: spotbulle_user
