service:
  # Service Frontend (React)
  - type: staticSite
    name: spotbulle-front-end
    env: node
    region: frankfurt
    plan: free
    rootDir: front-end
    buildFilter:
      paths:
        - "front-end/**"
    buildCommand: |
      npm install
      npm run build
      # Créer un fichier _redirects pour gérer le routage SPA
      echo "/* /index.html 200" > dist/_redirects
    startCommand: npx serve -s dist
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.19.1
      - key: VITE_API_URL
        value: https://spotbulle-backend.tydv.onrender.com
