services:
  # Frontend (React + Vite)
  - type: staticSite
    name: spotbulle-frontend
    region: frankfurt
    plan: free
    rootDir: front-end
    buildFilter:
      paths:
        - "front-end/**"
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: spotbulle-backend
          property: url
